[package]
name = "stusb4500-utils"
version = "0.2.0"
edition = "2021"

[dependencies]
stusb4500 = { path = "..", version = "0.2"}
clap = { version = "4.5.16", features = ["derive"] }
log = { version = "0.4" }

# HAL
linux-embedded-hal = "0.4"
env_logger = "0.11.5"
